import type { Flight, FlightStatusInfo, Destination, EuroBonusMember, Booking } from '../types';

export const mockFlights: Flight[] = [
  {
    id: 'fl-001',
    outbound: {
      flightNumber: 'SK 503',
      origin: { code: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Sweden' },
      destination: { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark' },
      departureTime: '2026-04-10T06:30:00',
      arrivalTime: '2026-04-10T07:55:00',
      duration: '1h 25m',
      aircraft: 'Airbus A320',
      stops: 0,
    },
    fares: [
      {
        id: 'fare-001-eco',
        cabinClass: 'economy',
        price: 899,
        currency: 'SEK',
        label: 'Airways Go',
        baggage: '1 cabin bag',
        changeable: false,
        refundable: false,
        pointsEarned: 450,
      },
      {
        id: 'fare-001-plus',
        cabinClass: 'plus',
        price: 1499,
        currency: 'SEK',
        label: 'Airways Plus',
        baggage: '1 checked bag + cabin',
        changeable: true,
        refundable: false,
        pointsEarned: 900,
      },
      {
        id: 'fare-001-biz',
        cabinClass: 'business',
        price: 3200,
        currency: 'SEK',
        label: 'Airways Business',
        baggage: '2 checked bags + cabin',
        changeable: true,
        refundable: true,
        pointsEarned: 2400,
      },
    ],
  },
  {
    id: 'fl-002',
    outbound: {
      flightNumber: 'SK 507',
      origin: { code: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Sweden' },
      destination: { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark' },
      departureTime: '2026-04-10T10:00:00',
      arrivalTime: '2026-04-10T11:25:00',
      duration: '1h 25m',
      aircraft: 'Airbus A319',
      stops: 0,
    },
    fares: [
      {
        id: 'fare-002-eco',
        cabinClass: 'economy',
        price: 1199,
        currency: 'SEK',
        label: 'Airways Go',
        baggage: '1 cabin bag',
        changeable: false,
        refundable: false,
        pointsEarned: 600,
      },
      {
        id: 'fare-002-plus',
        cabinClass: 'plus',
        price: 1899,
        currency: 'SEK',
        label: 'Airways Plus',
        baggage: '1 checked bag + cabin',
        changeable: true,
        refundable: false,
        pointsEarned: 1100,
      },
    ],
  },
  {
    id: 'fl-003',
    outbound: {
      flightNumber: 'SK 801',
      origin: { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark' },
      destination: { code: 'OSL', name: 'Oslo Gardermoen', city: 'Oslo', country: 'Norway' },
      departureTime: '2026-04-10T08:15:00',
      arrivalTime: '2026-04-10T09:30:00',
      duration: '1h 15m',
      aircraft: 'Boeing 737-800',
      stops: 0,
    },
    fares: [
      {
        id: 'fare-003-eco',
        cabinClass: 'economy',
        price: 749,
        currency: 'DKK',
        label: 'Airways Go',
        baggage: '1 cabin bag',
        changeable: false,
        refundable: false,
        pointsEarned: 375,
      },
    ],
  },
  {
    id: 'fl-004',
    outbound: {
      flightNumber: 'SK 1407',
      origin: { code: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Sweden' },
      destination: { code: 'LHR', name: 'London Heathrow', city: 'London', country: 'United Kingdom' },
      departureTime: '2026-04-10T09:00:00',
      arrivalTime: '2026-04-10T11:15:00',
      duration: '2h 15m',
      aircraft: 'Airbus A321',
      stops: 0,
    },
    fares: [
      {
        id: 'fare-004-eco',
        cabinClass: 'economy',
        price: 1899,
        currency: 'SEK',
        label: 'Airways Go',
        baggage: '1 cabin bag',
        changeable: false,
        refundable: false,
        pointsEarned: 750,
      },
      {
        id: 'fare-004-biz',
        cabinClass: 'business',
        price: 6500,
        currency: 'SEK',
        label: 'Airways Business',
        baggage: '2 checked bags + cabin',
        changeable: true,
        refundable: true,
        pointsEarned: 4500,
      },
    ],
  },
];

export const mockFlightStatus: FlightStatusInfo[] = [
  {
    flightNumber: 'SK 503',
    date: '2026-04-10',
    status: 'scheduled',
    origin: { code: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Sweden' },
    destination: { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark' },
    scheduledDeparture: '2026-04-10T06:30:00',
    estimatedDeparture: '2026-04-10T06:30:00',
    scheduledArrival: '2026-04-10T07:55:00',
    estimatedArrival: '2026-04-10T07:55:00',
    gate: 'C22',
    terminal: 'Terminal 5',
  },
  {
    flightNumber: 'SK 507',
    date: '2026-04-10',
    status: 'delayed',
    origin: { code: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Sweden' },
    destination: { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark' },
    scheduledDeparture: '2026-04-10T10:00:00',
    estimatedDeparture: '2026-04-10T10:40:00',
    scheduledArrival: '2026-04-10T11:25:00',
    estimatedArrival: '2026-04-10T12:05:00',
    gate: 'D14',
    terminal: 'Terminal 5',
    delay: 40,
  },
  {
    flightNumber: 'SK 801',
    date: '2026-04-10',
    status: 'boarding',
    origin: { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark' },
    destination: { code: 'OSL', name: 'Oslo Gardermoen', city: 'Oslo', country: 'Norway' },
    scheduledDeparture: '2026-04-10T08:15:00',
    estimatedDeparture: '2026-04-10T08:15:00',
    scheduledArrival: '2026-04-10T09:30:00',
    estimatedArrival: '2026-04-10T09:30:00',
    gate: 'B08',
    terminal: 'Pier B',
  },
];

export const mockDestinations: Destination[] = [
  {
    id: 'dest-cph',
    city: 'Copenhagen',
    country: 'Denmark',
    airportCode: 'CPH',
    imageUrl: 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800',
    description: 'A city of design, cycling, and world-class cuisine rooted in Nordic tradition.',
    priceFrom: 749,
    currency: 'SEK',
    tags: ['culture', 'design', 'food'],
    popular: true,
  },
  {
    id: 'dest-osl',
    city: 'Oslo',
    country: 'Norway',
    airportCode: 'OSL',
    imageUrl: 'https://images.unsplash.com/photo-1508189860359-777d945909ef?w=800',
    description: 'Fjords, museums and a thriving food scene nestled at the end of the Oslofjord.',
    priceFrom: 899,
    currency: 'SEK',
    tags: ['nature', 'fjords', 'museums'],
    popular: true,
  },
  {
    id: 'dest-hel',
    city: 'Helsinki',
    country: 'Finland',
    airportCode: 'HEL',
    imageUrl: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800',
    description: 'A vibrant design capital on the Baltic Sea with sauna culture and modern architecture.',
    priceFrom: 1099,
    currency: 'SEK',
    tags: ['design', 'sauna', 'architecture'],
    popular: true,
  },
  {
    id: 'dest-lhr',
    city: 'London',
    country: 'United Kingdom',
    airportCode: 'LHR',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
    description: 'Imperial history, world-class theatre, and a culinary scene that never sleeps.',
    priceFrom: 1899,
    currency: 'SEK',
    tags: ['history', 'culture', 'theatre'],
    popular: true,
  },
  {
    id: 'dest-nrt',
    city: 'Tokyo',
    country: 'Japan',
    airportCode: 'NRT',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    description: 'A dazzling metropolis where ancient temples stand beside futuristic towers.',
    priceFrom: 7999,
    currency: 'SEK',
    tags: ['culture', 'food', 'technology'],
    popular: false,
  },
  {
    id: 'dest-jfk',
    city: 'New York',
    country: 'USA',
    airportCode: 'JFK',
    imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
    description: "The city that never sleeps, offering art, fashion, and unparalleled energy.",
    priceFrom: 5499,
    currency: 'SEK',
    tags: ['city', 'fashion', 'art'],
    popular: true,
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'book-001',
    pnr: 'XKJP72',
    flight: mockFlights[0],
    selectedFare: mockFlights[0].fares[1],
    passengers: [
      {
        id: 'pax-001',
        firstName: 'Aman',
        lastName: 'Negi',
        dateOfBirth: '1985-03-14',
        passport: 'SE1293847',
        euroBonusNumber: 'EB123456789',
      },
    ],
    totalPrice: 1499,
    currency: 'SEK',
    status: 'confirmed',
    createdAt: '2026-03-15T12:00:00',
  },
  {
    id: 'book-002',
    pnr: 'RTYM93',
    flight: mockFlights[3],
    selectedFare: mockFlights[3].fares[0],
    passengers: [
      {
        id: 'pax-002',
        firstName: 'Aman',
        lastName: 'Negi',
        dateOfBirth: '1985-03-14',
        passport: 'SE1293847',
      },
    ],
    totalPrice: 1899,
    currency: 'SEK',
    status: 'confirmed',
    createdAt: '2026-03-18T09:30:00',
  },
];

export const mockMember: EuroBonusMember = {
  memberId: 'EB123456789',
  firstName: 'Aman',
  lastName: 'Negi',
  tier: 'silver',
  points: 24_500,
  tierPoints: 8_200,
  expiryDate: '2027-01-31',
};
